build: off

environment:
  matrix:
    - PYTHON: "C:\\Python27"
      PYTHON_VERSION: "2.7.8"
      PYTHON_ARCH: "32"

    - PYTHON: "C:\\Python34-x64"
      PYTHON_VERSION: "3.4.4"
      PYTHON_ARCH: "64"

    - PYTHON: "C:\\Python37-x64"
      PYTHON_VERSION: "3.7.0"
      PYTHON_ARCH: "64"

init:
  - ECHO %PYTHON% %PYTHON_VERSION% %PYTHON_ARCH%
  - "%PYTHON%/python --version"

install:
  - set PATH=%PYTHON%\\scripts;%PATH%
  - pip install pytest
  - py.test --version

  - pip install -e .

test_script:
  - py.test -v
