language: python

# Run jobs on container-based infrastructure, can be overridden per job
sudo: false

python:
  - "2.7"
  - "3.4"
  - "3.7"

before_install:
  - uname -a
  - free -m
  - df -h
  - ulimit -a

install:
  - pip install pytest pytest-cov flake8

before_script:
  - python -V

script:
  # Test style with flake8
  - flake8 . --count --show-source --statistics

  # Install source
  - pip install -e .

  # Test runtime with pytest and create report for codecov
  - py.test -v --cov=./

after_success:
  # Install and run codecov
  - pip install codecov
  - codecov

notifications:
  # Don't bother me
  email: false
