version: 2
jobs:
  test:
    docker:
      - image: python:latest
    steps:
      - checkout
      - run: python --version
      - run: pip install pytest
      - run: pip install -e .
      - run:
          name: Run pytest
          command: 'pytest -v'

workflows:
  version: 2
  ci:
    jobs:
      - test
